# Generated by Django 5.1.15 on 2026-05-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_payment_photo_bookingpaymentphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('pending_review', 'Pending Review'), ('paid_full', 'Paid')], default='unpaid', max_length=20),
        ),
    ]
