# Generated by Django 5.1.15 on 2026-05-20 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_booking_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='admin_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_type',
            field=models.CharField(choices=[('advance', 'Advance'), ('full', 'Full')], default='advance', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='remaining_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='subtotal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('upi', 'UPI'), ('card', 'Credit / Debit Card'), ('netbanking', 'Net Banking'), ('wallet', 'Wallet')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('pending_review', 'Pending Review'), ('paid_partial', 'Advance Paid'), ('paid_full', 'Paid Full')], default='unpaid', max_length=30),
        ),
    ]
