# Generated by Django 4.2.30 on 2026-05-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_admin_notes_booking_payment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
    ]
