# Generated by Django 5.1.15 on 2026-05-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_excerpt_event_location_event_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
